### ISSUE TITLE
Is the properties definition of the schema correct?

### ISSUE THREAD

**Issue by chrberndt** [zwischenloesung/ardu-report-lib#2]
I'd expected an array of (named) objects, e.g.

<pre>
{
    "$schema": "https://raw.githubusercontent.com/inofix/ardu-report-lib/master/schemas/meta-schema.json",
    "$id": "https://raw.githubusercontent.com/inofix/ardu-report-lib/master/schemas/default-schema.json",
    "title": "Default Sensor Data Schema",
    "description": "Definition of the inofix.ch arduino sensor data output JSON. (Customizations must only respect the key flag and may vary the property names. Please validate against this schema.)",
    "type": "array",
    "minItems": 1,
    "uniqueItems": true,
    "items": {
        "type": "object",
        "properties": [
            {"id": {
                "type": "string",
                "key": "id"
            }},
            {"value": {
                "type": "number",
                "key": "value"
            }},
            {"unit": {
                "type": "string",
                "key": "unit"
            }},
            {"threshold": {
                "type": "number",
                "key": "threshold"
            }}
        ],
        "minProperties": 2,
        "required": ["id", "value"]
    }
}
</pre>

**Comment by zwischenloesung** [comment]
Are you talking about the relation between meta-schema and schema or between schema and the final json? Maybe you can indicate where exactly the expectation does not meet the (current) reality.

**Comment by chrberndt** [comment]
misunderstood properties definition
