### ISSUE TITLE
Is there a way to indicate whether a value for a property is required or not?

### ISSUE THREAD

**Issue by chrberndt** [zwischenloesung/ardu-report-lib#3]
e.g. 

<pre>
            "value": {
                "type": "number",
                "key": "value",
                "required": true
            },
</pre>

**Comment by zwischenloesung** [comment]
The schema defines whether a property is required... see e.g. line 30 of https://github.com/zwischenloesung/ardu-report-lib/blob/master/schemas/default-schema.json:
 `"required": ["id", "value"]`

**Comment by chrberndt** [comment]
I see, thank you!
